//
//  ViewController.m
//  BBTestAppAutogeneratedSchemes
//
//  Created by Chris on 2015-06-23.
//  Copyright (c) 2015 BB. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
